import type { Metadata } from 'next';

import { RootLayout } from '@/components/root-layout';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RootLayout>
      <Header />
      {children}
      <Footer />
    </RootLayout>
  );
}
